<a href="https://colab.research.google.com/github/siberbot88/Data-sience-learning/blob/main/Intro_to_google_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introduction google Colab**


*   ctrl + enter = run
*   shift + enter = run + jump to next cell

*   alt + enter = insert a new code
*   List item

In [ ]:
a = 10
print(a)

10


In [ ]:
print(b)

15


In [ ]:
b = 15
b

15

#**Shell Command**

1. melihat direktori utama

In [ ]:
!ls

sample_data


2. melihat direktori file disimpan dalam folder

In [ ]:
!pwd

/content


#**Magics**

Magics itu adalah cara mengubah bagaimana suatu cell itu bekerja.
keyword sintax magics adalah (%)

1. cara melihat kecepatan sebuah code di eksekusi

In [ ]:
import numpy as np

%timeit np.linalg.eigvals(np.random.rand(100,100))

12.2 ms ± 3.57 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


2. Cara membuat magics sintax HTML

In [ ]:
%%HTML
<marquee style='width:30%; color: green;'>Hello world!</marquee>

#**Documentation**

1. Cara melihat dokumentasi module

In [ ]:
np.random?

#**Markdown**

**python** *programming*




[**My github**](https://github.com/siberbot88/Data-sience-learning.git)




**ordered List**
1. indonesia
1. belanda
1. portugis
1. jepang

**Unordered List**
* Indonesia
* Belanda
* Portugis
* Jepang

**Nested List**
* Belanda
  1. Belanda 1
  1. Belanda 2

**LaTex Syntax**
Use mathjax rendering

$\sqrt{9}+1$
$\sqrt{9}+1^3$

**Tabel**

Nama makanan | harga
--- | ---
nasi goreng | 15000
Es teh manis | 3500

#**Numpy**


In [5]:
import numpy as np



Array dengan rank 1 dan 3 elemen


In [ ]:
[1, 2, 3]

[1, 2, 3]

Array dengan rank 2 dan 3 elemen

In [ ]:
[[1, 2, 3 , 4], [5, 6, 7, 8]]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print('ini adalah array 1 dimensi \n',a)
print('ini adalah array 2 dimensi \n',b)

ini adalah array 1 dimensi 
 [1 2 3]
ini adalah array 2 dimensi 
 [[1 2 3]
 [4 5 6]]


**ndArray**: nama class untuk sebuah numpy array.

In [ ]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


#**Properties**
* *ndarray.ndim*: mengembalikan dimensi dari sebuah numpy array.
* *ndarray.shape*: mereturn jumlah baris dan colum dari sebuah numpy array.
* *ndarray.size*: jumlah elemen didalam numpuy array.
* *ndarray.dtype*: mencari tipe data dari elemen yang ada di numpy array.
* *ndarray.itemsize*: ukuran elemen (bytes) yang ada di numpy array.
* *ndarray.data*: sebuah buffer untuk menyimpan elemen-elemen di dalam numpy array.


In [8]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [10]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


#**Numpy Array**


* *np.zeros* : Isinya semua nol.
* *np.ones* : Isinya semua 1.
* *np.arange* : Bisa berikan scope dan panjang dari step.
* *np.linspace* : Bisa berikan scope dan jumlah elemen yang diinginkan.
* *np.random.random* : Memberikan angka acak.

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.arange(1, 5, 0.07)

array([1.  , 1.07, 1.14, 1.21, 1.28, 1.35, 1.42, 1.49, 1.56, 1.63, 1.7 ,
       1.77, 1.84, 1.91, 1.98, 2.05, 2.12, 2.19, 2.26, 2.33, 2.4 , 2.47,
       2.54, 2.61, 2.68, 2.75, 2.82, 2.89, 2.96, 3.03, 3.1 , 3.17, 3.24,
       3.31, 3.38, 3.45, 3.52, 3.59, 3.66, 3.73, 3.8 , 3.87, 3.94, 4.01,
       4.08, 4.15, 4.22, 4.29, 4.36, 4.43, 4.5 , 4.57, 4.64, 4.71, 4.78,
       4.85, 4.92, 4.99])

In [20]:
np.arange(1, 2, 0.11)

array([1.  , 1.11, 1.22, 1.33, 1.44, 1.55, 1.66, 1.77, 1.88, 1.99])

In [23]:
np.linspace(1, 3, 10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [27]:
np.random.random((7, 2))

array([[0.43603354, 0.1899466 ],
       [0.47467217, 0.0723298 ],
       [0.13339958, 0.00856192],
       [0.48549633, 0.45540569],
       [0.186149  , 0.07306904],
       [0.60368872, 0.80094797],
       [0.7711405 , 0.99007551]])

In [28]:
np.random.random((2, 3))

array([[0.77400612, 0.52913346, 0.43359935],
       [0.98414308, 0.91970514, 0.19238499]])

#**Shape Operations**

* *reshape* : mengubah dimensi/shape dari sebuah numpy array.
* *vstack* : stack numpy arrays secara vertikal.
* *hstack* : stack numpy arrays secara horizontal.
* *vsplit* : split numpy array secara vertikal.
* *hsplit* : split numpy array secara horizontal.

In [44]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
b = np.array([(7, 8,), (9, 10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [40]:
np.vstack((a, b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
c = np.array([(11, 12, 13), (14, 15, 16)])
c


array([[11, 12, 13],
       [14, 15, 16]])

In [48]:
d = np.hstack((a, c))
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [50]:
np.vsplit(d, 2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [52]:
np.hsplit(d, 3)

[array([[1, 2],
        [4, 5]]),
 array([[ 3, 11],
        [ 6, 14]]),
 array([[12, 13],
        [15, 16]])]

In [53]:
np.hsplit(d, (1, 3))

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]