<a href="https://colab.research.google.com/github/siberbot88/Data-sience-learning/blob/main/Intro_to_google_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introduction google Colab**


*   ctrl + enter = run
*   shift + enter = run + jump to next cell

*   alt + enter = insert a new code
*   List item

In [ ]:
a = 10
print(a)

10


In [ ]:
print(b)

15


In [ ]:
b = 15
b

15

#**Shell Command**

1. melihat direktori utama

In [ ]:
!ls

sample_data


2. melihat direktori file disimpan dalam folder

In [ ]:
!pwd

/content


#**Magics**

Magics itu adalah cara mengubah bagaimana suatu cell itu bekerja.
keyword sintax magics adalah (%)

1. cara melihat kecepatan sebuah code di eksekusi

In [ ]:
import numpy as np

%timeit np.linalg.eigvals(np.random.rand(100,100))

12.2 ms ± 3.57 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


2. Cara membuat magics sintax HTML

In [ ]:
%%HTML
<marquee style='width:30%; color: green;'>Hello world!</marquee>

#**Documentation**

1. Cara melihat dokumentasi module

In [ ]:
np.random?

#**Markdown**

**python** *programming*




[**My github**](https://github.com/siberbot88/Data-sience-learning.git)




**ordered List**
1. indonesia
1. belanda
1. portugis
1. jepang

**Unordered List**
* Indonesia
* Belanda
* Portugis
* Jepang

**Nested List**
* Belanda
  1. Belanda 1
  1. Belanda 2

**LaTex Syntax**
Use mathjax rendering

$\sqrt{9}+1$
$\sqrt{9}+1^3$

**Tabel**

Nama makanan | harga
--- | ---
nasi goreng | 15000
Es teh manis | 3500

#**Numpy**


In [5]:
import numpy as np



Array dengan rank 1 dan 3 elemen


In [ ]:
[1, 2, 3]

[1, 2, 3]

Array dengan rank 2 dan 3 elemen

In [ ]:
[[1, 2, 3 , 4], [5, 6, 7, 8]]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print('ini adalah array 1 dimensi \n',a)
print('ini adalah array 2 dimensi \n',b)

ini adalah array 1 dimensi 
 [1 2 3]
ini adalah array 2 dimensi 
 [[1 2 3]
 [4 5 6]]


**ndArray**: nama class untuk sebuah numpy array.

In [ ]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


#**Properties**
* *ndarray.ndim*: mengembalikan dimensi dari sebuah numpy array.
* *ndarray.shape*: mereturn jumlah baris dan colum dari sebuah numpy array.
* *ndarray.size*: jumlah elemen didalam numpuy array.
* *ndarray.dtype*: mencari tipe data dari elemen yang ada di numpy array.
* *ndarray.itemsize*: ukuran elemen (bytes) yang ada di numpy array.
* *ndarray.data*: sebuah buffer untuk menyimpan elemen-elemen di dalam numpy array.
